from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuscarTareaMainWindow(object):
    def setupUi(self, BuscarTareaMainWindow):
        BuscarTareaMainWindow.setObjectName("BuscarTareaMainWindow")
        BuscarTareaMainWindow.resize(1800, 880)
        BuscarTareaMainWindow.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"background-color: rgb(211, 211, 211);")
        self.centralwidget = QtWidgets.QWidget(BuscarTareaMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 70, 701, 41))
        self.label_3.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.BuscarTarea = QtWidgets.QLineEdit(self.centralwidget)
        self.BuscarTarea.setGeometry(QtCore.QRect(270, 220, 341, 41))
        self.BuscarTarea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.BuscarTarea.setObjectName("BuscarTarea")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(270, 290, 881, 591))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 881, 221))
        self.frame.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Titulo = QtWidgets.QLabel(self.frame)
        self.Titulo.setGeometry(QtCore.QRect(0, 0, 281, 31))
        self.Titulo.setMaximumSize(QtCore.QSize(1080, 1920))
        self.Titulo.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.Titulo.setObjectName("Titulo")
        self.Descripcion = QtWidgets.QLabel(self.frame)
        self.Descripcion.setGeometry(QtCore.QRect(0, 40, 401, 131))
        self.Descripcion.setWordWrap(True)
        self.Descripcion.setObjectName("Descripcion")
        self.fechavencimiento = QtWidgets.QLabel(self.frame)
        self.fechavencimiento.setGeometry(QtCore.QRect(550, 40, 181, 131))
        self.fechavencimiento.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.fechavencimiento.setWordWrap(True)
        self.fechavencimiento.setObjectName("fechavencimiento")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(430, 0, 151, 41))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 0, 141, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.recordatorio = QtWidgets.QLabel(self.frame)
        self.recordatorio.setGeometry(QtCore.QRect(730, 0, 151, 171))
        self.recordatorio.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.recordatorio.setWordWrap(True)
        self.recordatorio.setObjectName("recordatorio")
        self.AgregarRecordatorio = QtWidgets.QPushButton(self.frame)
        self.AgregarRecordatorio.setGeometry(QtCore.QRect(750, 10, 121, 23))
        self.AgregarRecordatorio.setObjectName("AgregarRecordatorio")
        self.Eliminar = QtWidgets.QPushButton(self.frame)
        self.Eliminar.setGeometry(QtCore.QRect(620, 0, 51, 41))
        self.Eliminar.setObjectName("Eliminar")
        self.Editar = QtWidgets.QPushButton(self.frame)
        self.Editar.setGeometry(QtCore.QRect(670, 0, 61, 41))
        self.Editar.setObjectName("Editar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Nombredepersona = QtWidgets.QLabel(self.centralwidget)
        self.Nombredepersona.setGeometry(QtCore.QRect(260, 120, 211, 41))
        self.Nombredepersona.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.Nombredepersona.setObjectName("Nombredepersona")
        BuscarTareaMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BuscarTareaMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 21))
        self.menubar.setObjectName("menubar")
        BuscarTareaMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BuscarTareaMainWindow)
        self.statusbar.setObjectName("statusbar")
        BuscarTareaMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BuscarTareaMainWindow)
        QtCore.QMetaObject.connectSlotsByName(BuscarTareaMainWindow)

    def retranslateUi(self, BuscarTareaMainWindow):
        _translate = QtCore.QCoreApplication.translate
        BuscarTareaMainWindow.setWindowTitle(_translate("BuscarTareaMainWindow", "Buscar Tarea"))
        self.label_3.setText(_translate("BuscarTareaMainWindow", "Bienvenido a tu gestor de tareas"))
        self.Titulo.setText(_translate("BuscarTareaMainWindow", "TextLabel"))
        self.Descripcion.setText(_translate("BuscarTareaMainWindow", "TextLabel"))
        self.fechavencimiento.setText(_translate("BuscarTareaMainWindow", "TextLabel"))
        self.comboBox.setItemText(0, _translate("BuscarTareaMainWindow", "Media"))
        self.comboBox.setItemText(1, _translate("BuscarTareaMainWindow", "alto"))
        self.comboBox.setItemText(2, _translate("BuscarTareaMainWindow", "bajo"))
        self.comboBox_2.setItemText(0, _translate("BuscarTareaMainWindow", "Completa"))
        self.comboBox_2.setItemText(1, _translate("BuscarTareaMainWindow", "Incompleta"))
        self.comboBox_2.setItemText(2, _translate("BuscarTareaMainWindow", "Pendiente"))
        self.recordatorio.setText(_translate("BuscarTareaMainWindow", "TextLabel"))
        self.AgregarRecordatorio.setText(_translate("BuscarTareaMainWindow", "Agregar recordatorio"))
        self.Eliminar.setText(_translate("BuscarTareaMainWindow", "Eliminar"))
        self.Editar.setText(_translate("BuscarTareaMainWindow", "Editar"))
        self.Nombredepersona.setText(_translate("BuscarTareaMainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BuscarTareaMainWindow = QtWidgets.QMainWindow()
    ui = Ui_BuscarTareaMainWindow()
    ui.setupUi(BuscarTareaMainWindow)
    BuscarTareaMainWindow.show()
    sys.exit(app.exec_())
