# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MensajeEliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from Backend.Tarea import Tarea





class Ui_Eliminar(object):
    def setupUi(self, MainWindow,id_tarea,id_usuario,mostrar_tareas):
        self.mostrar_tareas = mostrar_tareas
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 192)
        MainWindow.setMaximumSize(QtCore.QSize(406, 192))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VentanaEliminar = QtWidgets.QFrame(self.centralwidget)
        self.VentanaEliminar.setGeometry(QtCore.QRect(0, 0, 401, 161))
        self.VentanaEliminar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VentanaEliminar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VentanaEliminar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VentanaEliminar.setObjectName("VentanaEliminar")
        self.LetraEliminar = QtWidgets.QLabel(self.VentanaEliminar)
        self.LetraEliminar.setGeometry(QtCore.QRect(30, 20, 321, 31))
        self.LetraEliminar.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"")
        self.LetraEliminar.setObjectName("LetraEliminar")
        self.Textoabajo = QtWidgets.QLabel(self.VentanaEliminar)
        self.Textoabajo.setGeometry(QtCore.QRect(40, 60, 301, 16))
        self.Textoabajo.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Textoabajo.setObjectName("Textoabajo")

        self.label = QtWidgets.QLabel(self.VentanaEliminar)
        self.label.setGeometry(QtCore.QRect(20, 100, 51, 41))
        self.label.setPixmap(QtGui.QPixmap("C:/Users/ivanv/Desktop/GestorTareas/GestordeTareas1.0/Interfaz/iconos/peligro.png"))  # Cargar la imagen
        self.label.setObjectName("label")
        self.label.setScaledContents(True)

        self.BotonCancelar = QtWidgets.QPushButton(self.VentanaEliminar)
        self.BotonCancelar.setGeometry(QtCore.QRect(200, 120, 91, 31))
        self.BotonCancelar.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.BotonCancelar.setObjectName("BotonCancelar")
        self.BotonCancelar.clicked.connect(lambda _ :self.Cancelar())

        self.BotonAceptar = QtWidgets.QPushButton(self.VentanaEliminar)
        self.BotonAceptar.setGeometry(QtCore.QRect(300, 120, 91, 31))
        self.BotonAceptar.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.BotonAceptar.setObjectName("BotonAceptar")
        self.BotonAceptar.clicked.connect(lambda _: self.EliminarTarea(id_tarea,id_usuario))



        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 406, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LetraEliminar.setText(_translate("MainWindow", "Deseas eliminar la Tarea?"))
        self.Textoabajo.setText(_translate("MainWindow", "Si eliminas esta tarea, no podras recuperarla."))
        self.BotonCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.BotonAceptar.setText(_translate("MainWindow", "Aceptar"))

    def EliminarTarea(self,id_tarea,id_usuario):
        Elitarea = Tarea()
        exito,mesaje =Elitarea.eliminar_tarea(id_tarea,id_usuario)
        if exito:
            self.centralwidget.window().close()
            self.mostrar_tareas(id_usuario)
    def Cancelar(self):
        self.centralwidget.window().close()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Eliminar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
