# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from Tarea import Tarea
from Categoria import Categoria
from Etiqueta import Etiqueta
from Interfaz.AgregarTarea import Ui_Agregar_MainWindow as Uiagregar
from BuscarTarea import Ui_BuscarTareaMainWindow as UiBuscar
from PyQt5 import QtWidgets
from PyQt5.QtCore import (QCoreApplication, QMetaObject, QRect, QSize)
from PyQt5.QtGui import ( QFont, QPixmap)
from PyQt5.QtWidgets import *
import icono_rc
from PyQt5.QtGui import QIcon
from Interfaz.AgregarRecordatorio import Ui_MainWindow as UiRecordatorio
from Interfaz.MensajeEliminar import Ui_Eliminar as UiEliminar
from Interfaz.EditarTarea import Ui_Editar_MainWindow as UiEditar





class Ui_MainWindow(object):

    def setupUi(self, MainWindow,id_usuario, nombre):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 880)
        MainWindow.setMaximumSize(QtCore.QSize(2000, 1920))
        MainWindow.setStyleSheet("background-color: rgb(219, 219, 219);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 0, 701, 50))
        self.label_3.setStyleSheet("font: bold 28pt 'MS Shell Dlg 2';")
        self.label_3.setObjectName("label_3")

        self.Nombredepersona = QtWidgets.QLabel(self.centralwidget)
        self.Nombredepersona.setGeometry(QtCore.QRect(380, 50, 550, 41))
        self.Nombredepersona.setStyleSheet("font: bold 28pt 'MS Shell Dlg 2';")
        self.Nombredepersona.setObjectName("Nombredepersona")
        self.Nombredepersona.setText(nombre)
        self.Nombredepersona.setText("")
        self.Nombredepersona.setText( nombre)


        # Scroll Area Setup
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(390, 220, 950, 591))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet("QScrollArea { border: none; }")


        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # Layout para las tareas
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.BuscarTarea = QtWidgets.QPushButton(self.centralwidget)
        self.BuscarTarea.setGeometry(QtCore.QRect(390, 150, 341, 41))
        self.BuscarTarea.setStyleSheet("background-color: rgb(255, 255, 255); font: 15pt 'MS Shell Dlg 2';")
        self.BuscarTarea.setObjectName("BuscarTarea")
        self.BuscarTarea.clicked.connect(self.AbrirBuscarTarea)  # Conectar al metodo

        self.BotonAgregarTarea = QtWidgets.QPushButton(self.centralwidget)
        self.BotonAgregarTarea.setGeometry(QtCore.QRect(1150, 160, 121, 41))
        self.BotonAgregarTarea.setObjectName("BotonAgregarTarea")
        self.BotonAgregarTarea.setStyleSheet(u"QPushButton {\n"
                                        "	color: rgb(255, 255, 255);\n"
                                        "	border-radius:15px;\n"
                                        "	background-color: rgb(30, 30, 30);\n"
                                        "   font-size: 16px;\n            " 
                                        "}\n"
                                        "QPushButton:Hover {\n"
                                        "	border-bottom: 2px solid blue;\n"
                                        "	background-color: rgb(30, 30, 30);\n"
                                        "\n"
                                        "}")
        self.BotonAgregarTarea.clicked.connect(self.AbrirAgregarTarea) # Conectar al metodo

        self.iconolibro = QLabel(self.centralwidget)
        self.iconolibro.setObjectName(u"iconolibro")
        self.iconolibro.setGeometry(QRect(280, 20, 81, 71))
        self.iconolibro.setPixmap(QPixmap(u":/icono/libro-abierto.png"))
        self.iconolibro.setScaledContents(True)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.mostrar_tareas(id_usuario)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Bienvenido a tu gestor de tareas"))
        self.BotonAgregarTarea.setText(_translate("MainWindow", "Agregar Tarea"))
        self.iconolibro.setText("")

    def agregarTarea(self):
        # Crear un nuevo frame con la estructura original de la tarea
        nuevaTarea = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        nuevaTarea.setMinimumSize(QtCore.QSize(0, 221))
        nuevaTarea.setStyleSheet("background-color: rgb(221, 221, 221);")
        nuevaTarea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        nuevaTarea.setFrameShadow(QtWidgets.QFrame.Raised)

        titulo = QtWidgets.QLabel(nuevaTarea)
        titulo.setGeometry(QtCore.QRect(0, 0, 281, 31))
        titulo.setMaximumSize(QtCore.QSize(1080, 1920))
        titulo.setStyleSheet("font: 20pt 'MS Shell Dlg 2';")
        titulo.setText("Nueva Tarea")

        descripcion = QtWidgets.QLabel(nuevaTarea)
        descripcion.setGeometry(QtCore.QRect(0, 40, 401, 131))
        descripcion.setWordWrap(True)
        descripcion.setText("Descripción de la nueva tarea")

        fechavencimiento = QtWidgets.QLabel(nuevaTarea)
        fechavencimiento.setGeometry(QtCore.QRect(550, 40, 181, 131))
        fechavencimiento.setStyleSheet("background-color: rgb(154, 154, 154);")
        fechavencimiento.setWordWrap(True)
        fechavencimiento.setText("Fecha de vencimiento")

        comboBox_prioridad = QtWidgets.QComboBox(nuevaTarea)
        comboBox_prioridad.setGeometry(QtCore.QRect(430, 0, 151, 41))
        comboBox_prioridad.setStyleSheet("background-color: rgb(255, 255, 255);")
        comboBox_prioridad.addItem("Media")
        comboBox_prioridad.addItem("Alta")
        comboBox_prioridad.addItem("Baja")

        comboBox_estado = QtWidgets.QComboBox(nuevaTarea)
        comboBox_estado.setGeometry(QtCore.QRect(290, 0, 141, 41))
        comboBox_estado.setStyleSheet("background-color: rgb(255, 255, 255);")
        comboBox_estado.addItem("🟢Completa")
        comboBox_estado.addItem("🔴Incompleta")
        comboBox_estado.addItem("🟨Pendiente")

        recordatorio = QtWidgets.QLabel(nuevaTarea)
        recordatorio.setGeometry(QtCore.QRect(730, 0, 151, 171))
        recordatorio.setStyleSheet("background-color: rgb(154, 154, 154);")
        recordatorio.setWordWrap(True)
        recordatorio.setText("Recordatorio")

        # Botones Eliminar y Editar
        boton_eliminar = QtWidgets.QPushButton(nuevaTarea)
        boton_eliminar.setGeometry(QtCore.QRect(620, 0, 51, 41))
        boton_eliminar.setText("Eliminar")

        boton_editar = QtWidgets.QPushButton(nuevaTarea)
        boton_editar.setGeometry(QtCore.QRect(670, 0, 61, 41))
        boton_editar.setText("Editar")

        boton_recordatorio = QtWidgets.QPushButton(nuevaTarea)
        boton_recordatorio.setGeometry(QtCore.QRect(750, 10, 100, 25))  # Ancho, Altura
        boton_recordatorio.setText("Recordatorio")

        # Agregar el nuevo frame al layout vertical
        self.verticalLayout.addWidget(nuevaTarea)

    def mostrar_tareas(self,id_usuario):
        print("Llamando a obtener_tareas_usuario()...")

        tarea_obj = Tarea()
        tareas = tarea_obj.obtener_tareas_usuario(id_usuario)  # Cambia 30 por el ID de usuario correcto

        if tareas is None:
            print("Error: No se pudieron obtener las tareas.")
            return

        print(f"Se obtuvieron {len(tareas)} tareas.")

        # Limpiar el layout actual antes de mostrar las nuevas tareas
        for i in reversed(range(self.verticalLayout.count())):
            widget = self.verticalLayout.itemAt(i).widget()
            if widget is not None:
                widget.deleteLater()

        # Si no hay tareas, mostrar un mensaje
        if not tareas:
            no_tareas_label = QtWidgets.QLabel("No hay tareas para mostrar.", self.scrollAreaWidgetContents)
            self.verticalLayout.addWidget(no_tareas_label)
            print("No se encontraron tareas para mostrar.")
            return  # Salir de la función si no hay tareas

        # Si hay tareas, agregar cada una a la interfaz
        for tarea in tareas:
            print(f"Agregando tarea con ID: {tarea[0]} y título: {tarea[1]}")
            nueva_tarea = QtWidgets.QFrame(self.scrollAreaWidgetContents)
            nueva_tarea.setMinimumSize(QtCore.QSize(0, 221))
            nueva_tarea.setStyleSheet("""
                QFrame {
                    background-color: rgb(221, 221, 221);
                }
                QFrame#nueva_tarea {
                    border: 1px solid black;
                }
            """)
            nueva_tarea.setObjectName("nueva_tarea")  # Asignar un nombre de objeto único
            nueva_tarea.setFrameShape(QtWidgets.QFrame.StyledPanel)
            nueva_tarea.setFrameShadow(QtWidgets.QFrame.Raised)

            titulo = QtWidgets.QLabel(nueva_tarea)
            titulo.setGeometry(QtCore.QRect(10, 10, 281, 31))
            titulo.setStyleSheet("font: 20pt 'MS Shell Dlg 2'; font-weight: bold;")
            titulo.setText(tarea[1])  # Usar el título de la tarea

            descripcion = QtWidgets.QTextEdit(nueva_tarea)
            descripcion.setGeometry(QtCore.QRect(5, 55, 500, 131))  # Ajustar el tamaño inicial
            descripcion.setText(tarea[2])  # Usar la descripción de la tarea
            descripcion.setReadOnly(True)
            descripcion.setStyleSheet("border: none; background: transparent;")

            fecha_vencimiento = QtWidgets.QLabel(nueva_tarea)
            fecha_vencimiento.setGeometry(QtCore.QRect(550,0, 251, 220))
            fecha_vencimiento.setStyleSheet("background-color: rgb(154, 154, 154);")
            fecha_vencimiento.setWordWrap(True)
            fecha_vencimiento.setText(f"Vencimiento: {tarea[3]}")  # Usar la fecha de vencimiento

            comboBox_categoria = QtWidgets.QComboBox(nueva_tarea)
            comboBox_categoria.setGeometry(QtCore.QRect(430, 0, 151, 41))
            comboBox_categoria.setStyleSheet("background-color: rgb(255, 255, 255);")
            comboBox_categoria.addItem(tarea[4])
            comboBox_categoria.addItems(['Completa','Incompleta','Pendiente'])  # Agrega tus categorías

            # Conectar el evento de cambio del ComboBox a la función de actualización de categoría
            comboBox_categoria.currentIndexChanged.connect(
                lambda index, id_tarea=tarea[0]: self.actualizar_categoria(id_tarea, comboBox_categoria.itemText(index),
                                                                           id_usuario)
            )
            comboBox_categoria.setStyleSheet("""
                QComboBox {
                    background-color: rgb(255, 255, 255);
                    color: rgb(0, 0, 0);
                    border-radius: 10px;  /* Borde redondeado */
                    padding: 5px;
                    border: 1px solid rgb(100, 100, 100);
                }

                QComboBox:hover {
                    border: 1px solid rgb(0, 122, 204);  /* Borde azul al pasar el mouse */
                }

                QComboBox QAbstractItemView {
                    background-color: rgb(255, 255, 255);  /* Fondo del menú desplegable */
                    selection-background-color: rgb(0, 122, 204);  /* Color de selección */
                    selection-color: rgb(255, 255, 255);  /* Texto blanco al seleccionar */
                }
            """)

            comboBox_etiqueta = QtWidgets.QComboBox(nueva_tarea)
            comboBox_etiqueta.setGeometry(QtCore.QRect(290, 0, 141, 41))
            comboBox_etiqueta.setStyleSheet("background-color: rgb(255, 255, 255);")
            comboBox_etiqueta.addItem(tarea[5])# Usar el estado de la tarea
            comboBox_etiqueta.addItems(['Alta','Media','Baja'])


            comboBox_etiqueta.currentIndexChanged.connect(
                lambda index,id_tarea=tarea[0]: self.actualizar_etiqueta(id_tarea,id_usuario,comboBox_etiqueta.itemText(index))
            )
            comboBox_etiqueta.setStyleSheet("""
                QComboBox {
                    background-color: rgb(255, 255, 255);
                    color: rgb(0, 0, 0);
                    border-radius: 10px;  /* Borde redondeado */
                    padding: 5px;
                    border: 1px solid rgb(100, 100, 100);
                }

                QComboBox:hover {
                    border: 1px solid rgb(0, 122, 204);  /* Borde azul al pasar el mouse */
                }

                QComboBox QAbstractItemView {
                    background-color: rgb(255, 255, 255);  /* Fondo del menú desplegable */
                    selection-background-color: rgb(0, 122, 204);  /* Color de selección */
                    selection-color: rgb(255, 255, 255);  /* Texto blanco al seleccionar */
                }
            """)

            recordatorio = QtWidgets.QLabel(nueva_tarea)
            recordatorio.setGeometry(QtCore.QRect(730, 0, 300, 220))
            recordatorio.setStyleSheet("background-color: rgb(154, 154, 154);")
            recordatorio.setWordWrap(True)
            recordatorio.setText(f"Recordatorio")

            # Crear el botón de eliminar
            boton_eliminar = QtWidgets.QPushButton(nueva_tarea)
            boton_eliminar.setGeometry(QtCore.QRect(620, 0, 51, 41))
            icono_eliminar = QIcon(r"C:\Users\ivanv\Desktop\GestorTareas\GestordeTareas1.0\Interfaz\iconos\basura.png")  # Cambia el nombre del archivo a tu icono
            boton_eliminar.setIcon(icono_eliminar)
            boton_eliminar.setIconSize(QtCore.QSize(32, 32))

            boton_eliminar.clicked.connect(lambda _, id_tarea=tarea[0]: self.EliminarTarea(id_tarea, id_usuario))



            boton_editar = QtWidgets.QPushButton(nueva_tarea)
            boton_editar.setGeometry(QtCore.QRect(670, 0, 61, 41))
            icono_editar = QIcon(r"C:\Users\ivanv\Desktop\GestorTareas\GestordeTareas1.0\Interfaz\iconos\boton-editar.png")
            boton_editar.setIcon(icono_editar)
            boton_editar.setIconSize(QtCore.QSize(32, 32))
            boton_editar.clicked.connect(lambda _, id_tarea=tarea[0]: self.EditarTarea(id_tarea, id_usuario))


            boton_recordatorio = QtWidgets.QPushButton(nueva_tarea)
            boton_recordatorio.setGeometry(QtCore.QRect(748, 10, 150, 25))  # Ancho, Altura
            boton_recordatorio.setText("Agregar Recordatorio")
            boton_recordatorio.setStyleSheet(u"QPushButton {\n"
                                            "	color: rgb(255, 255, 255);\n"
                                            "	border-radius:15px;\n"
                                            "	background-color: rgb(30, 30, 30);\n"
                                            "}\n"
                                            "QPushButton:Hover {\n"
                                            "	border-bottom: 2px solid blue;\n"
                                            "	background-color: rgb(30, 30, 30);\n"
                                            "\n"
                                            "}")

            boton_recordatorio.clicked.connect(self.AbrirRecordatorio)
            self.verticalLayout.addWidget(nueva_tarea)
        else:
            no_tareas_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            self.verticalLayout.addWidget(no_tareas_label)

    def actualizar_categoria(self, id_tarea, categoria_seleccionada, id_usuario):
        print(f"Intentando actualizar la categoría de la tarea ID: {id_tarea} a '{categoria_seleccionada}'.")
        if categoria_seleccionada != "Selecciona Categoría":
            categoria_obj = Categoria()  # Crear una instancia de Categoria
            categoria_obj.asignar_categoria(id_tarea, id_usuario, categoria_seleccionada)  # Asignar la categoría
            print(f"Categoría '{categoria_seleccionada}' asignada a la tarea ID: {id_tarea}.")
        else:
            print("Por favor, selecciona una categoría válida.")


    def actualizar_etiqueta(self,id_tarea,id_usuario,etiqueta_seleccionada):
        nueva_etiqueta=Etiqueta()
        nueva_etiqueta.asignar_etiqueta(id_tarea,id_usuario,etiqueta_seleccionada)
        print(f"etiqueta '{etiqueta_seleccionada}' asignada a la tarea ID: {id_tarea}.")



    def AbrirAgregarTarea(self,id_usuario):
        self.window = QtWidgets.QMainWindow()  # Crear una nueva ventana
        self.ui = Uiagregar()  # Usar la clase de la segunda ventana
        self.ui.setupUi(self.window,id_usuario)  # Inicializar la segunda ventana
        self.window.show()


    def AbrirRecordatorio(self):
        self.window = QtWidgets.QMainWindow()  # Crear una nueva ventana
        self.ui = UiRecordatorio()  # Usar la clase de la segunda ventana
        self.ui.setupUi(self.window)  # Inicializar la segunda ventana
        self.window.show()  # Mostrar la

    def AbrirBuscarTarea(self):
        self.window = QtWidgets.QMainWindow()  # Crear una nueva ventana
        self.ui = UiBuscar()  # Usar la clase de la segunda ventana
        self.ui.setupUi(self.window)  # Inicializar la segunda ventana
        self.window.show()  # Mostrar la

    def EliminarTarea(self,id_tarea,id_usuario):
        self.window = QtWidgets.QMainWindow()  # Crear una nueva ventana
        self.ui = UiEliminar()  # Usar la clase de la segunda ventana
        self.ui.setupUi(self.window)  # Inicializar la segunda ventana
        self.window.show()

    def EditarTarea(self,id_tarea, id_usuario):
        self.window = QtWidgets.QMainWindow()  # Crear una nueva ventana
        self.ui = UiEditar()  # Usar la clase de la segunda ventana
        self.ui.setupUi(self.window)  # Inicializar la segunda ventana
        self.window.show()





if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
