# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from usuario import Usuarios


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 800))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(380, 180, 371, 461))
        self.widget.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.INombre = QtWidgets.QTextEdit(self.widget)
        self.INombre.setGeometry(QtCore.QRect(60, 40, 241, 41))
        self.INombre.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.INombre.setObjectName("INombre")
        self.INCorreo = QtWidgets.QTextEdit(self.widget)
        self.INCorreo.setGeometry(QtCore.QRect(60, 120, 241, 41))
        self.INCorreo.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.INCorreo.setObjectName("INCorreo")
        self.INContrasena = QtWidgets.QTextEdit(self.widget)
        self.INContrasena.setGeometry(QtCore.QRect(60, 210, 241, 41))
        self.INContrasena.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.INContrasena.setObjectName("INContrasena")
        self.INcontrasena2 = QtWidgets.QTextEdit(self.widget)
        self.INcontrasena2.setGeometry(QtCore.QRect(60, 290, 241, 41))
        self.INcontrasena2.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.INcontrasena2.setObjectName("INcontrasena2")
        self.BotonRegistro = QtWidgets.QPushButton(self.widget)
        self.BotonRegistro.setGeometry(QtCore.QRect(100, 400, 151, 48))
        self.BotonRegistro.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.BotonRegistro.setObjectName("BotonRegistro")
        self.Nombre = QtWidgets.QLabel(self.widget)
        self.Nombre.setEnabled(True)
        self.Nombre.setGeometry(QtCore.QRect(60, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Nombre.setFont(font)
        self.Nombre.setStyleSheet("color: rgb(231, 231, 231);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(190, 190, 190);\n"
"\n"
"")
        self.Nombre.setTextFormat(QtCore.Qt.PlainText)
        self.Nombre.setObjectName("Nombre")
        self.Email = QtWidgets.QLabel(self.widget)
        self.Email.setEnabled(True)
        self.Email.setGeometry(QtCore.QRect(60, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Email.setFont(font)
        self.Email.setStyleSheet("color: rgb(231, 231, 231);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(190, 190, 190);\n"
"\n"
"")
        self.Email.setTextFormat(QtCore.Qt.PlainText)
        self.Email.setObjectName("Email")
        self.Contrasena = QtWidgets.QLabel(self.widget)
        self.Contrasena.setEnabled(True)
        self.Contrasena.setGeometry(QtCore.QRect(60, 180, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Contrasena.setFont(font)
        self.Contrasena.setStyleSheet("color: rgb(231, 231, 231);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(190, 190, 190);\n"
"\n"
"")
        self.Contrasena.setTextFormat(QtCore.Qt.PlainText)
        self.Contrasena.setObjectName("Contrasena")
        self.ConfirmarContra = QtWidgets.QLabel(self.widget)
        self.ConfirmarContra.setEnabled(True)
        self.ConfirmarContra.setGeometry(QtCore.QRect(60, 260, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ConfirmarContra.setFont(font)
        self.ConfirmarContra.setStyleSheet("color: rgb(231, 231, 231);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(190, 190, 190);\n"
"\n"
"")
        self.ConfirmarContra.setTextFormat(QtCore.Qt.PlainText)
        self.ConfirmarContra.setObjectName("ConfirmarContra")
        self.MensajeEmergente = QtWidgets.QLabel(self.widget)
        self.MensajeEmergente.setGeometry(QtCore.QRect(30, 350, 301, 41))
        self.MensajeEmergente.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 4);")
        self.MensajeEmergente.setAlignment(QtCore.Qt.AlignCenter)
        self.MensajeEmergente.setWordWrap(True)
        self.MensajeEmergente.setObjectName("MensajeEmergente")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setEnabled(True)
        self.Titulo.setGeometry(QtCore.QRect(380, 120, 371, 68))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Titulo.setFont(font)
        self.Titulo.setStyleSheet("color: rgb(231, 231, 231);\n"
"\n"
"font: 87 36pt \"Arial Black\";\n"
"background-color: rgb(190, 190, 190);\n"
"\n"
"")
        self.Titulo.setTextFormat(QtCore.Qt.PlainText)
        self.Titulo.setIndent(0)
        self.Titulo.setObjectName("Titulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.BotonRegistro.clicked.connect(self.registrarusuarios)#conectar al boton

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BotonRegistro.setText(_translate("MainWindow", "Registrarse"))
        self.Nombre.setText(_translate("MainWindow", "Nombre"))
        self.Email.setText(_translate("MainWindow", "Email"))
        self.Contrasena.setText(_translate("MainWindow", "Contrasena"))
        self.ConfirmarContra.setText(_translate("MainWindow", "Confirmar Contrasena"))
        self.MensajeEmergente.setText(_translate("MainWindow", "MensajeEmergente"))
        self.MensajeEmergente.setText("")
        self.Titulo.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/>hhh</p></body></html>"))
        self.Titulo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Titulo.setText(_translate("MainWindow", "Registrarse"))



    def registrarusuarios(self):
        nombre = self.INombre.toPlainText().strip()
        correo = self.INCorreo.toPlainText().strip()
        contrasena = self.INContrasena.toPlainText().strip()
        confirmar_contrasena = self.INcontrasena2.toPlainText().strip()


        # Crear instancia de Usuarios y asignar datos
        usuario = Usuarios(nombre, correo, contrasena,confirmar_contrasena)

        # Registrar el usuario
        registro_exitoso,mensaje = usuario.registrarusuarios()

        if registro_exitoso:
            print("Usuario registrado correctamente desde la interfaz gráfica.")
            self.centralwidget.window().hide() #oculta la ventana de registro en vez de cerrarla

        else:
            self.MensajeEmergente.setText(mensaje)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
